name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    uses: oodles-noodles/reusable-workflows/.github/workflows/build-and-push.yml@main
    with:
      registry: ${{ vars.ACR_REGISTRY }}
      image_name: ${{ github.event.repository.name }}
      azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
      artifact-metadata: write
