name: Deploy to AKS

on:
  workflow_run:
    workflows: ["Build and Push to Azure Container Registry"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: oodles-noodles/reusable-workflows/.github/workflows/deploy.yml@main
    with:
      registry: ${{ vars.ACR_REGISTRY }}
      image_name: ${{ github.event.repository.name }}
      azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      aks_resource_group: ${{ vars.AKS_RESOURCE_GROUP }}
      aks_cluster_name: ${{ vars.AKS_CLUSTER_NAME }}
      helm_chart_path: "./helm/secure-chainz"
      helm_release_name: "secure-chainz"
      head_sha: ${{ github.event.workflow_run.head_sha }}
    permissions:
      contents: read
      id-token: write
      deployments: write
      artifact-metadata: write
